# run on container-based infrastructure
sudo: false

language: python

addons:
    apt:
        packages:
            - gfortran

env:
  global:
    # wradlib-docs
    - secure: "DBk2O2mxCSqMz5g3E1hpIB9brFR/7HiKQRjwa3GLndTl6ksI24tfbcoBl2+wHMmRKSn1Un3NrlsxHL8IwwwkG5fBjCwdKPwxvAGBXKU+cbvYAcaUCIuU0JMYMHli+jSUq6vWSoVUE72olX6Flo3tPBl6iBOcUZGia1ZrI3NhtDljwMLh5K/vuacPaZCrYgBVCkEglu1EYfAE2lhdQKxQwP1kGXpcUZ3vSC44yYsqjvaOjiMl+Zo3kQ/5DO8yYxVdp2R7Nb6/Y51Yc1S6V0xE1/QfK2HbUmgikLsxY8cISaTPKB0dOuoxNSVKkmBw6zaDPhCi4NSSuQgtSUqiEn+CF4Mljapp2AVp5mmITEV7S+7Cje+mHZbWNEdlpXzOMWscwtp/kpSpOUHLL0qIZ2zhJocIt0r8bQAyLaI3SxyyAiypsLMaqixDnH3jQ3Q+Fghx3wMPHnucuPYZkzQrz2mFz/hZ0LVPm6m0Jhzqdf2IJx6CSxg47UPpm2gvcr5gch7GYzCOkfcIzJFlk/OkpHGXBmvy0jQI3KFrlA+kCJvS944rCCS+F37v6N/aMoxsiU8VWyf0urp1Y6zhu/oPRFGGpRkjjc5jdNJIxytk8WFRSesntshT/7YEQMa/hj+QYyrIeWcq4gR4OpabU8Gt4jx/KP5XTNp+QgchHBV/BoThilo="
    - NOTEBOOKS_BUILD_DIR=$TRAVIS_BUILD_DIR

matrix:
    include:
    - python: 3.6
      env:
        - PYTHON_VERSION="3.6"

install:
    - deactivate
    - source scripts/install.sh

before_script:
    - export GDAL_DATA=$HOME/miniconda/envs/wradlib/share/gdal
    - export WRADLIB_DATA=$HOME/wradlib-data
    - export WRADLIB_NOTEBOOKS=$NOTEBOOKS_BUILD_DIR/notebooks
    - export DISPLAY=:99
    - sh -e /etc/init.d/xvfb start
    - sleep 3

script:
    - scripts/render_notebooks.sh

after_success:
    - cd $NOTEBOOKS_BUILD_DIR && scripts/push_notebooks.sh
